### ISSUE TITLE
streamlit run failing

### ISSUE THREAD

**Issue by jdgh000** [Stability-AI/generative-models#119]
ubuntu 22.04 + cuda 12.2
streamlist runs ok, but when accessed through browser, script.demo error occurs.

```

streamlit run scripts/demo/sampling.py --server.port 7680

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://10.0.0.188:7680
  External URL: http://73.71.55.152:7680

2023-08-26 03:15:43.306 Uncaught app exception
Traceback (most recent call last):
  File "/root/gg/git/hf/generative-models/.pt13/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/root/gg/git/hf/generative-models/scripts/demo/sampling.py", line 3, in <module>
    from scripts.demo.streamlit_helpers import *
ModuleNotFoundError: No module named 'scripts.demo'

ModuleNotFoundError: No module named 'scripts.demo'
Traceback:
File "/root/gg/git/hf/generative-models/.pt13/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/root/gg/git/hf/generative-models/scripts/demo/sampling.py", line 3, in <module>
    from scripts.demo.streamlit_helpers import *

```

**Comment by moutasemalakkad** [comment]
Same issue here

**Comment by dongkuang** [comment]
PYTHONPATH=. streamlit run scripts/demo/sampling.py --server.port 1234

**Comment by moutasemalakkad** [comment]
I ran the command like so and still getting the same issue

streamlit run scripts/demo/sampling.py --server.port 1234

**Comment by moutasemalakkad** [comment]
set the python path like so to fix the issue
export PYTHONPATH=/<>/generative-models:$PYTHONPATH

and then run the streamlit command

**Comment by parzoe** [comment]
> PYTHONPATH=. streamlit run scripts/demo/sampling.py --server.port 1234

This solution worked for me. Thankx

**Comment by huitang96** [comment]
if on the windows,
set PYTHONPATH=. streamlit run scripts\demo\sampling.py --server.port 1234

**Comment by Fearblade66** [comment]
PYTHONPATH=. streamlit run scripts/demo/sampling.py --server.port 1234
Doesnt work and
PYTHONPATH=. 
streamlit run scripts/demo/sampling.py --server.port 1234
Doesnt work, and i even went and edited the python path in windows itself :/
