### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by maxlestage** [Stability-AI/generative-models#125]
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/maxlestage/Documents/generative-models/.pt2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/maxlestage/Documents/generative-models/.pt2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/maxlestage/Documents/generative-models/.pt2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/2x/m4ycq1yx2v96bbd0vg9sxqzr0000gn/T/pip-build-env-9slo9dmn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/2x/m4ycq1yx2v96bbd0vg9sxqzr0000gn/T/pip-build-env-9slo9dmn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2x/m4ycq1yx2v96bbd0vg9sxqzr0000gn/T/pip-build-env-9slo9dmn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/2x/m4ycq1yx2v96bbd0vg9sxqzr0000gn/T/pip-build-env-9slo9dmn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(.pt2) user@mbp-de-user generative-models %

**Comment by maxlestage** [comment]
Hello  i don't understand but after i tried to run from the install instruction and i get this error at end, anyone can help me ?

**Comment by osster** [comment]
Had the same error at Mac M3, Python 3.10.11. Problem solved due 
`pip install torchvision`

**Comment by richardlamo** [comment]
I'm using an M1Pro and I'm also getting this error even after I 

> pip install torchvision

Any ideas?

**Comment by 0xbohu** [comment]
Same issue with Apple M1Pro, already installed torchvision
```
pip3 install torchvision
```

```
>>> import torchvision
>>> print(torchvision.__version__)
0.17.1
```

Anyone has luck with M1pro?
