### ISSUE TITLE
img2vid No module named 'scripts.util'

### ISSUE THREAD

**Issue by veryVANYA** [Stability-AI/generative-models#138]
Trying to run new video model but watermark filter not being detected.

Traceback (most recent call last):
  File "C:\AI\Video\StableVideo\generative_models_main\scripts\sampling\simple_video_sample.py", line 16, in <module>
    from scripts.util.detection.nsfw_and_watermark_dectection import DeepFloydDataFiltering
ModuleNotFoundError: No module named 'scripts.util'

**Comment by Viliars** [comment]
> Trying to run new video model but watermark filter not being detected.
> 
> Traceback (most recent call last): File "C:\AI\Video\StableVideo\generative_models_main\scripts\sampling\simple_video_sample.py", line 16, in from scripts.util.detection.nsfw_and_watermark_dectection import DeepFloydDataFiltering ModuleNotFoundError: No module named 'scripts.util'

You need to add "generative_models_main" to PYTHONPATH

**Comment by alexfredo** [comment]
I have the same problem and I added the folder in pythonpath 
![testttpath](https://github.com/Stability-AI/generative-models/assets/24534698/a07201c3-6bc3-4ae3-9ad6-cac0d76a7712)

**Comment by becausecurious** [comment]
On linux the following works for me:

> PYTHONPATH=.  streamlit run  scripts/demo/video_sampling.py --server.port 8005

from generative-models root.

(source: https://github.com/Stability-AI/generative-models/issues/119#issuecomment-1707643530)

**Comment by alexfredo** [comment]
Thanks ! for windows we need to enter first  : set PYTHONPATH=.
and then : streamlit run scripts/demo/video_sampling.py --server.port 8005

**Comment by kingljl** [comment]
> Thanks !

Thanks !

**Comment by kingljl** [comment]
> On linux the following works for me:
> 
> > PYTHONPATH=.  streamlit run  scripts/demo/video_sampling.py --server.port 8005
> 
> from generative-models root.
> 
> (source: [#119 (comment)](https://github.com/Stability-AI/generative-models/issues/119#issuecomment-1707643530))

Thanks !
