### ISSUE TITLE
SVD: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType

### ISSUE THREAD

**Issue by hudbrog** [Stability-AI/generative-models#139]
All stable video models via example streamlit app are failing to load with the same error:
```
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/svd.safetensors
2023-11-21 21:21:20.648 Uncaught app exception
Traceback (most recent call last):
  File "/workspace/generative-models/.pt2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/workspace/generative-models/scripts/demo/video_sampling.py", line 142, in <module>
    value_dict["cond_frames"] = img + cond_aug * torch.randn_like(img)
TypeError: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType
```

environment:
```
# python --version
Python 3.10.12

# md5sum checkpoints/*
5c58a3cdfe7c8dd35aac83ce55ab087e  checkpoints/svd.safetensors
3c4a68b929ea5b45f7329b3bc3fd497b  checkpoints/svd_xt.safetensors
bec00900734f25e0c52638c1aa75b4e7  checkpoints/svd_xt_image_decoder.safetensors
```

**Comment by Viliars** [comment]
> All stable video models via example streamlit app are failing to load with the same error:
> 
> ```
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> VideoTransformerBlock is using checkpointing
> Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
> Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
> Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
> Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
> Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
> Loading model from checkpoints/svd.safetensors
> 2023-11-21 21:21:20.648 Uncaught app exception
> Traceback (most recent call last):
>   File "/workspace/generative-models/.pt2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
>     exec(code, module.__dict__)
>   File "/workspace/generative-models/scripts/demo/video_sampling.py", line 142, in <module>
>     value_dict["cond_frames"] = img + cond_aug * torch.randn_like(img)
> TypeError: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType
> ```
> 
> environment:
> 
> ```
> # python --version
> Python 3.10.12
> 
> # md5sum checkpoints/*
> 5c58a3cdfe7c8dd35aac83ce55ab087e  checkpoints/svd.safetensors
> 3c4a68b929ea5b45f7329b3bc3fd497b  checkpoints/svd_xt.safetensors
> bec00900734f25e0c52638c1aa75b4e7  checkpoints/svd_xt_image_decoder.safetensors
> ```

The error seems to be related to the fact that streamlet is trying to run the model before you uploaded the image.
If you just ignore this error and upload an image, everything will work.

**Comment by RuoyuFeng** [comment]
![1700621169412](https://github.com/Stability-AI/generative-models/assets/31685350/d9fa481e-6669-4ed2-8ce7-5d32f62c6f19)
@Viliars 
Hi, so how can I upload an image. It seems that I cannot find a botton to do that. Something wrong with my page?

**Comment by alexfredo** [comment]
Just select the model and click load model 
![helppp](https://github.com/Stability-AI/generative-models/assets/24534698/bfcc9df0-df39-4d85-9c6a-2818e8b617d2)

**Comment by RuoyuFeng** [comment]
@alexfredo 
Hi, thanks for your help. But when I select the same model as you choose, I got this page. The side bar at the left is different from yours, seems lost somthing including sampler and more. Besides, no button to upload the image has shown.
![1700627111583](https://github.com/Stability-AI/generative-models/assets/31685350/6e093e2a-ae90-4361-a3c6-2f86fd079371)

When I switch from Edge browser to Chrome, it seems works fine.
![image](https://github.com/Stability-AI/generative-models/assets/31685350/269c8b25-e7d9-44d6-981f-9147d4159d46)

**Comment by alexfredo** [comment]
Yes I use microsoft edge for the browser

**Comment by RuoyuFeng** [comment]
> Yes I use microsoft edge for the browser, its weird that he doesn't work on your computer you have updated edge ? My version is : Microsoft Edge Version 119.0.2151.72 (Version officielle) (64 bits)

My version is:
Version 119.0.2151.72 (Official build) (64-bit)Version 119.0.2151.72 (Official build) (64-bit)

It's really weired, but nevermind, thanks for your help! @ @alexfredo
