### ISSUE TITLE
omegaconf.errors.ConfigKeyError: Missing key devices

### ISSUE THREAD

**Issue by Toisoi** [Stability-AI/generative-models#160]
windows 11, CPU.
Error while running main.py

```C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.0)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
LOGDIR: logs\2023-11-22T18-54-42
Global seed set to 23
Using default TF32 settings for PyTorch 2.0.1+cpu:
torch.backends.cuda.matmul.allow_tf32=False
torch.backends.cudnn.allow_tf32=True
Traceback (most recent call last):
  File "C:\Projects\python\generative-models-0.1.0\main.py", line 655, in <module>
    gpuinfo = trainer_config["devices"]
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "C:\Projects\python\generative-models-0.1.0\.pt2\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key devices
    full_key: devices
    object_type=dict

**Comment by dyvniy** [comment]
No fix yet?
Debian 12, RTX 3090Ti, Xenon e5 2699 x2
```
LOGDIR: logs/2024-12-02T03-22-50
Seed set to 23
Using default TF32 settings for PyTorch 2.5.1+cu124:
torch.backends.cuda.matmul.allow_tf32=False
torch.backends.cudnn.allow_tf32=True
Traceback (most recent call last):
  File "/home/user/git/generative-models/main.py", line 655, in <module>
    gpuinfo = trainer_config["devices"]
              ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "/home/user/git/generative-models/venv/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key devices
    full_key: devices
    object_type=dict
```

**Comment by alex-oprst** [comment]
Hi @dyvniy 
I am also trying to solve this problem. 
What version of Python do you have?

I use Python 3.10.6 and torch 2.0.1+cu118 (I get exactly the same error)

**From installation instructions:**
`NOTE: This is tested under python3.10. For other python versions, you might encounter version conflicts.`

Maybe it makes sense to try this way?
