### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by dillfrescott** [Stability-AI/generative-models#163]
```
Traceback (most recent call last):
  File "/workspace/generative-models/.pt2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/workspace/generative-models/scripts/demo/sampling.py", line 332, in <module>
    out = run_img2img(
  File "/workspace/generative-models/scripts/demo/sampling.py", line 190, in run_img2img
    sampler, num_rows, num_cols = init_sampling(
  File "/workspace/generative-models/scripts/demo/streamlit_helpers.py", line 360, in init_sampling
    sampler = get_sampler(sampler, steps, discretization_config, guider_config, key=key)
  File "/workspace/generative-models/scripts/demo/streamlit_helpers.py", line 408, in get_sampler
    sampler = EulerEDMSampler(
  File "/workspace/generative-models/sgm/modules/diffusionmodules/sampling.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/workspace/generative-models/sgm/modules/diffusionmodules/sampling.py", line 32, in __init__
    self.guider = instantiate_from_config(
  File "/workspace/generative-models/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
TypeError: VanillaCFG.__init__() got an unexpected keyword argument 'scale_schedule_config'
```

**Comment by 5shekel** [comment]
pull the repo, its fixed
