### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts'

### ISSUE THREAD

**Issue by mikeyimer** [Stability-AI/generative-models#169]
When starting the UI, an error occurs:
E:\GITHUB\generative-models\.pt2\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
2023-11-23 14:24:04.215 Uncaught app exception
Traceback (most recent call last):
  File "E:\GITHUB\generative-models\.pt2\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\GITHUB\generative-models\scripts\demo\sampling.py", line 3, in <module>
    from scripts.demo.streamlit_helpers import *
ModuleNotFoundError: No module named 'scripts'

![图片](https://github.com/Stability-AI/generative-models/assets/137673481/b237856d-4708-454e-81c5-a06c6c84819e)

**Comment by yanzm4** [comment]
您需要将“generative_models_main”添加到 PYTHONPATH

export PYTHONPATH=$PYTHONPATH:root/image2video/generative-models

**Comment by mikeyimer** [comment]
> 您需要将“generative_models_main”添加到 PYTHONPATH
> 
> export PYTHONPATH=$PYTHONPATH:root/image2video/generative-models

Thanks, solved!

**Comment by MotorCityCobra** [comment]
The equivalent is not working for me on Windows 10


(base) (.pt2) C:\Users\ooo\tor\generative-models>set PYTHONPATH=%PYTHONPATH%;C:/Users/ooo/tor/generative-models/generative-models

(base) (.pt2) C:\Users\ooo\tor\generative-models>
(base) (.pt2) C:\Users\ooo\tor\generative-models>
(base) (.pt2) C:\Users\ooo\tor\generative-models>streamlit run scripts/sampling/simple_video_sample.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.244:8501

2023-11-26 21:41:08.292 Uncaught app exception
Traceback (most recent call last):
  File "c:\users\ooo\tor\generative-models\.pt2\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\ooo\tor\generative-models\scripts\sampling\simple_video_sample.py", line 16, in <module>
    from scripts.util.detection.nsfw_and_watermark_dectection import \
ModuleNotFoundError: No module named 'scripts'
2023-11-26 21:41:08.292 Uncaught app exception
Traceback (most recent call last):
  File "c:\users\ooo\tor\generative-models\.pt2\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\ooo\tor\generative-models\scripts\sampling\simple_video_sample.py", line 16, in <module>
    from scripts.util.detection.nsfw_and_watermark_dectection import \
ModuleNotFoundError: No module named 'scripts'

**Comment by lchustc** [comment]
> streamlit run scripts/sampling/simple_video_sample.py

I have the same problem

**Comment by yangyang940927** [comment]
I have the same problem to

**Comment by kacperadach** [comment]
same here
