### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by NeptuneNep** [Stability-AI/generative-models#178]
what are these errors and how to fix them, please tell me

xFormers can't load C++/CUDA extensions. xFormers was built for

AssertionError: Torch not compiled with CUDA enabled

warnings.warn("No audio backend is available.")
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/svd.safetensors
2023-11-23 16:41:58.724 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\TheVirgin\anaconda3\envs\genModelVideo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\TheVirgin\generative-models\video_sampling.py", line 142, in <module>
    value_dict["cond_frames"] = img + cond_aug * torch.randn_like(img)
TypeError: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType
2023-11-23 16:42:17.780 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\TheVirgin\anaconda3\envs\genModelVideo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\TheVirgin\generative-models\video_sampling.py", line 137, in <module>
    img = load_img_for_prediction(W, H)
  File "C:\Users\TheVirgin\generative-models\scripts\demo\streamlit_helpers.py", line 849, in load_img_for_prediction
    return image.to(device) * 2.0 - 1.0
  File "C:\Users\TheVirgin\anaconda3\envs\genModelVideo\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by nbertagnolli** [comment]
Are you running this on a machine with a CUDA compatible GPU? It looks like the model is being sent to a gpu. If you're running on a CPU you'll need to change all calls `.to(device)` to `.to("cpu")`

**Comment by NeptuneNep** [comment]
I have an msi gtx 3050

> Вы запускаете это на компьютере с графическим процессором, совместимым с CUDA? Похоже, что модель отправляется на графический процессор. Если вы работаете на процессоре, вам нужно будет изменить все вызовы `.to(device)` на `.to("cpu")`

**Comment by NeptuneNep** [comment]
> Are you running this on a machine with a CUDA compatible GPU? It looks like the model is being sent to a gpu. If you're running on a CPU you'll need to change all calls `.to(device)` to `.to("cpu")`

I have an msi gtx 3050
