### ISSUE TITLE
UnboundLocalError: local variable 'grid' referenced before assignment

### ISSUE THREAD

**Issue by keepacat** [Stability-AI/generative-models#181]
streamlit_helpers.py  in line 779
`grid = rearrange(grid, "n b c h w -> (n h) (b w) c")`

UnboundLocalError: local variable 'grid' referenced before assignment
It seems like one line is missing
`grid = torch.stack([samples])`

**Comment by dillfrescott** [comment]
Same error:

```
File "/workspace/generative-models/.pt2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/workspace/generative-models/scripts/demo/sampling.py", line 332, in <module>
    out = run_img2img(
File "/workspace/generative-models/scripts/demo/sampling.py", line 197, in run_img2img
    out = do_img2img(
File "/workspace/generative-models/.pt2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
File "/workspace/generative-models/scripts/demo/streamlit_helpers.py", line 779, in do_img2img
    grid = rearrange(grid, "n b c h w -> (n h) (b w) c")
```

**Comment by tekntrash** [comment]
same

**Comment by GrigoryPrutskov** [comment]
```
Sampler: EulerEDMSampler
Discretization: Img2ImgDiscretizationWrapper
Guider: VanillaCFG
Sampling with EulerEDMSampler for 30 steps:   0%|                                                                                                                                                                    | 0/30 [00:00<?, ?it/s]/home/microfocus/generative-models/.pt2/lib64/python3.9/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Sampling with EulerEDMSampler for 30 steps:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 29/30 [00:56<00:01,  1.95s/it]
2023-12-01 17:04:28.931 Uncaught app exception
Traceback (most recent call last):
  File "/home/microfocus/generative-models/.pt2/lib64/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/microfocus/generative-models/scripts/demo/sampling.py", line 332, in <module>
    out = run_img2img(
  File "/home/microfocus/generative-models/scripts/demo/sampling.py", line 197, in run_img2img
    out = do_img2img(
  File "/home/microfocus/generative-models/.pt2/lib64/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/microfocus/generative-models/scripts/demo/streamlit_helpers.py", line 779, in do_img2img
    grid = rearrange(grid, "n b c h w -> (n h) (b w) c")
UnboundLocalError: local variable 'grid' referenced before assignment

```

**Comment by devkan** [comment]
I get the same error with img2img.
How do I fix it?

```bash
##############################  Sampling setting  ##############################
Sampler: EulerEDMSampler
Discretization: Img2ImgDiscretizationWrapper
Guider: VanillaCFG
Sampling with EulerEDMSampler for 30 steps:  97%|████████████████████████▋  | 29/30 [00:11<00:00,  2.62it/s] 
2023-12-07 21:40:51.465 Uncaught app exception
Traceback (most recent call last):
  File "D:\Work\Python\04.Stable_Video_Diffusion\generative-models\.pt2\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\Work\Python\04.Stable_Video_Diffusion\generative-models\scripts\demo\sampling.py", line 332, in <module>
    out = run_img2img(
  File "D:\Work\Python\04.Stable_Video_Diffusion\generative-models\scripts\demo\sampling.py", line 197, in run_img2img
    out = do_img2img(
  File "D:\Work\Python\04.Stable_Video_Diffusion\generative-models\.pt2\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Work\Python\04.Stable_Video_Diffusion\generative-models\scripts\demo\streamlit_helpers.py", line 779, in do_img2img
    grid = rearrange(grid, "n b c h w -> (n h) (b w) c")
UnboundLocalError: local variable 'grid' referenced before assignment
```

**Comment by dust-demons** [comment]
just open the file "\scripts\demo\streamlit_helpers.py" in an editor 
and  add  this code  before line 779
```
grid = torch.stack([samples]) 
```
