### ISSUE TITLE
VanillaCFG.__init__() got an unexpected keyword argument 'dyn_thresh_config'

### ISSUE THREAD

**Issue by YingkaiD** [Stability-AI/generative-models#221]
Traceback (most recent call last):
  File "/data/yingkai/sdxl/generative-models/tests/inference/test_text_to_image.py", line 23, in <module>
    i2t = pipeline.text_to_image(
  File "/home/yingkai/anaconda3/envs/sdxl/lib/python3.10/site-packages/sgm/inference/api.py", line 192, in text_to_image
    sampler = get_sampler_config(params)
  File "/home/yingkai/anaconda3/envs/sdxl/lib/python3.10/site-packages/sgm/inference/api.py", line 370, in get_sampler_config
    return DPMPP2MSampler(
  File "/home/yingkai/anaconda3/envs/sdxl/lib/python3.10/site-packages/sgm/modules/diffusionmodules/sampling.py", line 32, in __init__
    self.guider = instantiate_from_config(
  File "/home/yingkai/anaconda3/envs/sdxl/lib/python3.10/site-packages/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
TypeError: VanillaCFG.__init__() got an unexpected keyword argument 'dyn_thresh_config'

**Comment by SWHL** [comment]
I met the same error. When I read the source code, I found that the `dyn_thresh_config` only appears in one place:

https://github.com/Stability-AI/generative-models/blob/fbdc58cab9f4ee2be7a5e1f2e2787ecd9311942f/sgm/inference/api.py#L290-L300

But in the directory of `sgm.modules.diffusionmodules.sampling_utils.NoDynamicThresholding`, I couldn't find the implementation of this function.

Finally I commented out this parameter as follows, and the program can run successfully.

```python
        guider_config = {
            "target": "sgm.modules.diffusionmodules.guiders.VanillaCFG",
            "params": {"scale": scale},
            # "params": {"scale": scale, "dyn_thresh_config": dyn_thresh_config},
        }
```
