### ISSUE TITLE
watermark error

### ISSUE THREAD

**Issue by kalle07** [Stability-AI/generative-models#234]
............
  Local URL: http://localhost:8501
  Network URL: http://192.168.7.21:8501

E:\generative-models\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
2023-12-06 18:54:03.411 Uncaught app exception
Traceback (most recent call last):
  File "E:\generative-models\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\generative-models\scripts\demo\video_sampling.py", line 5, in <module>
    from scripts.demo.streamlit_helpers import *
  File "E:\generative-models\scripts\demo\streamlit_helpers.py", line 26, in <module>
    from sgm.inference.helpers import embed_watermark
  File "E:\generative-models\sgm\inference\helpers.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'
2023-12-06 18:54:03.411 Uncaught app exception
Traceback (most recent call last):
  File "E:\generative-models\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\generative-models\scripts\demo\video_sampling.py", line 5, in <module>
    from scripts.demo.streamlit_helpers import *
  File "E:\generative-models\scripts\demo\streamlit_helpers.py", line 26, in <module>
    from sgm.inference.helpers import embed_watermark
  File "E:\generative-models\sgm\inference\helpers.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'
........

i tryed to install
pip install imWatermark

but nothing change

**Comment by lckj2009** [comment]
pip install invisible-watermark

**Comment by kalle07** [comment]
thx  ;)

next error:
  File "E:\generative-models\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\generative-models\scripts\demo\sampling.py", line 3, in <module>
    from scripts.demo.streamlit_helpers import *
ModuleNotFoundError: No module named 'scripts.demo'

i follow the steps on
https://github.com/Stability-AI/generative-models
and 
https://github.com/Stability-AI/generative-models/issues/172

why i must install all pagages with hand (already installed 7 packeges cause allways say "modulenotfound..." ?
(win10 with 4060RTX, powershel, with created env)

thy for help

**Comment by PathFinderMRX** [comment]
Del triton in the requirements then rest libs would be fine
https://github.com/Stability-AI/generative-models/issues/41#issuecomment-1642300606
About the error of 'ModuleNotFoundError: No module named 'scripts.demo'' you could try add the sys path before import:
```
import sys
sys.path.insert(0, 'your root path')
```
