### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key sampler_config

### ISSUE THREAD

**Issue by LolerPanda** [Stability-AI/generative-models#259]
When I python simple_video_sample.py, there is the issue:
`Traceback (most recent call last):
  File "/home/wangboyang-b21/generative-models-main/scripts/sampling/simple_video_sample.py", line 282, in <module>
    Fire(sample)
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/wangboyang-b21/generative-models-main/scripts/sampling/simple_video_sample.py", line 71, in sample
    model, filter = load_model(
  File "/home/wangboyang-b21/generative-models-main/scripts/sampling/simple_video_sample.py", line 267, in load_model
    config.model.params.sampler_config.params.num_steps = num_steps
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/wangboyang-b21/generative-models-main/.pt2/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key sampler_config
    full_key: model.params.sampler_config
    object_type=dict`

**Comment by monkey2627** [comment]
i met the same error.Have you fixed it?

**Comment by LolerPanda** [comment]
It's too long ago problem~ I guess you can copy sampler_config into the path.
