### ISSUE TITLE
[BUG]The following bugs have appeared in 'img2img'

### ISSUE THREAD

**Issue by lckj2009** [Stability-AI/generative-models#265]
**The following bugs:**

prune index: 22
sigmas after pruning:  tensor([3.6758, 3.3211, 3.0098, 2.7355, 2.4925, 2.2765, 2.0834, 1.9103, 1.7542,
        1.6129, 1.4844, 1.3672, 1.2596, 1.1606, 1.0690, 0.9838, 0.9044, 0.8299,
        0.7597, 0.6932, 0.6299, 0.5693, 0.5108, 0.4538, 0.3977, 0.3417, 0.2843,
        0.2230, 0.1515, 0.0000], device='cuda:0')
##############################  Sampling setting  ##############################
Sampler: EulerEDMSampler
Discretization: Img2ImgDiscretizationWrapper
Guider: VanillaCFG
Sampling with EulerEDMSampler for 30 steps:  97%|████████████████████████████████████████████████████████████▉  | 29/30 [00:01<00:00, 25.26it/s]
2024-01-02 13:56:58.410 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/pt2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/root/generative-models/scripts/demo/sampling.py", line 332, in <module>
    out = run_img2img(
  File "/root/generative-models/scripts/demo/sampling.py", line 197, in run_img2img
    out = do_img2img(
  File "/root/anaconda3/envs/pt2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/generative-models/scripts/demo/streamlit_helpers.py", line 779, in do_img2img
    grid = rearrange(grid, "n b c h w -> (n h) (b w) c")
UnboundLocalError: local variable 'grid' referenced before assignment

**Comment by YoucanBaby** [comment]
Same question
