### ISSUE TITLE
FileNotFoundError: No such file or directory: "checkpoints/svd.safetensors"

### ISSUE THREAD

**Issue by oXEKo** [Stability-AI/generative-models#287]
> VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/svd.safetensors
2024-02-24 22:24:10.002 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\generative-models-main\scripts\demo\video_sampling.py", line 120, in <module>
    state = init_st(version_dict, load_filter=True)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 268, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 324, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "C:\generative-models-main\scripts\demo\streamlit_helpers.py", line 46, in init_st
    model, msg = load_model_from_config(config, ckpt if load_ckpt else None)
  File "C:\generative-models-main\scripts\demo\streamlit_helpers.py", line 98, in load_model_from_config
    sd = load_safetensors(ckpt)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "checkpoints/svd.safetensors"

**Comment by KazusaKitakawa** [comment]
same question.

**Comment by Mercurise** [comment]
same question +1

**Comment by KazusaKitakawa** [comment]
> same question +1

I renamed the model file and problem solved (:

**Comment by kei971031** [comment]
download checkpoints manually.

mkdir checkpoints & cd checkpoints & run script below

```
from huggingface_hub import snapshot_download
from huggingface_hub import login
login() # login token needed! you can get token from huggingface profile
import os
os.environ['CURL_CA_BUNDLE'] = ''
snapshot_download(repo_id="stabilityai/stable-video-diffusion-img2vid-xt", local_dir="./")
```

note that this repo is svd-xt version(25frame), you can change repo_id if 14frame version needed.
