### ISSUE TITLE
Now i am developing a text to image model using stable diffusion. Here, i got an error i try to fix these but i don't how to do that. so anyone can help me?

### ISSUE THREAD

**Issue by Kowshiknarayan** [Stability-AI/generative-models#303]
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 443, in main
    accelerator = Accelerator(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 286, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/rkn', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/rkn/instance_images', '--output_dir=/content/models/rkn', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/rkn/captions', '--instance_prompt=', '--seed=757869', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=200']' returned non-zero exit status 1.
Something went wrong

**Comment by ayan4m1** [comment]
> ValueError: fp16 mixed precision requires a GPU

You need the CUDA version of pytorch installed.

**Comment by Kowshiknarayan** [comment]
I was using google collab. I change the runtime then it automatically runs the code. but, there is an new issue i occurred, I was using stable diffusion model to build model. here, in google collab they mentioned to you need to pay premium to test your model. so, i can't completely build the model. I train model completely after that, it generates a IP address. but, i need a link to put this IP in that link then only completely build this model.
