### ISSUE TITLE
Hello, why do I only generate one frame of video using sv3d_u and sv3d_p

### ISSUE THREAD

**Issue by kaikaizhangdragonplus** [Stability-AI/generative-models#320]
执行结果：python scripts/sampling/simple_video_sample.py --input_path assets/test_image.png --version sv3d_u
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Restored from checkpoints/sv3d_u.safetensors with 0 missing and 0 unexpected keys
/opt/dragonplus/generative-models/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")

或者：
streamlit run scripts/demo/video_sampling.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  Network URL: http://10.10.11.84:8501
  External URL: http://154.64.226.13:8501

VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/sv3d_u.safetensors
576 576 None
2024-03-21 18:52:16.771 Uncaught app exception
Traceback (most recent call last):
  File "/opt/dragonplus/generative-models/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/opt/dragonplus/generative-models/scripts/demo/video_sampling.py", line 192, in <module>
    value_dict["cond_frames"] = img + cond_aug * torch.randn_like(img)
TypeError: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType

**Comment by litter-bird-big-dream** [comment]
你好，请问下，你有没有遇到ConnectionResetError: [Errno 104] Connection reset by peer类似的报错？我一开始遇到huggingface.io访问不到的错误，修改地址，解决了，后来发现报了个新的错误。

我提交的两个问题：[https://github.com/Stability-AI/generative-models/issues/315][https://github.com/Stability-AI/generative-models/issues/123]

感觉是因为我的网络导致的，无法下载一些其他依赖的在线模型，

期待回复，谢谢！

**Comment by JinSeoung-Oh** [comment]
@kaikaizhangdragonplus 
Hi, I don't know my answer is right, 
but it seems that the issue mostly arises due to the imageio library. 
Therefore, instead of imageio, you can save frame by frame using cv2. 
However, looking at your error logs... it seems there might be a need to check the input data. 
The fact that a NoneType was passed as input data implies that either the input data is corrupted or the path was incorrectly set, resulting in failure to read it.

Thanks!

**Comment by zoldaten** [comment]
its imagio issue. seek for it here.

sould be something like this:
```
                #imageio.mimwrite(video_path, vid)
                #cv2.imwrite(video_path, vid)
                frame0 = vid[0, :, :, :].squeeze()
                out = cv2.VideoWriter(
                    video_path,
                    cv2.VideoWriter_fourcc(*"MP4V"),
                    20.0,
                    (frame0.shape[1], frame0.shape[0]),
                )
                for frame in vid:
                    out.write(frame[:, :, ::-1])
                out.release()
```

**Comment by wyweiyangweiGh** [comment]
Same issue.

**Comment by wyweiyangweiGh** [comment]
problem solved?

**Comment by lydonchandra** [comment]
> its imagio issue. seek for it here.
> 
> sould be something like this:
> 
> ```
>                 #imageio.mimwrite(video_path, vid)
>                 #cv2.imwrite(video_path, vid)
>                 frame0 = vid[0, :, :, :].squeeze()
>                 out = cv2.VideoWriter(
>                     video_path,
>                     cv2.VideoWriter_fourcc(*"MP4V"),
>                     20.0,
>                     (frame0.shape[1], frame0.shape[0]),
>                 )
>                 for frame in vid:
>                     out.write(frame[:, :, ::-1])
>                 out.release()
> ```

Thank you very much, confirmed this worked for me.

**Comment by gracesolver** [comment]
same here
