### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kalle07** [Stability-AI/generative-models#328]
sry... must i install somewhat ?

clone 
https://github.com/Stability-AI/generative-models.git

create directory "checkpoints"
download 
sv3d_u.safetensors
copy there

cmd (win10)

e:\stability_video>python scripts/sampling/simple_video_sample.py --input_path <image.png> --version sv3d_u
Traceback (most recent call last):
  File "e:\stability_video\scripts\sampling\simple_video_sample.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by hsebik** [comment]
You should install these packages inside requirements/pt2.txt  No module named 'cv2' is caused by not installed opencv-python==4.6.0.66.

**Comment by kalle07** [comment]
python3 -m venv .pt2
activate.bat

(.pt2) pip install -r pt2.txt


install ...

in the end

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0

install 
pip3 install .
pip3 install -e git+https://github.com/Stability-AI/datapipelines.git@main#egg=sdata
pip install hatch
hatch build -t wheel



and again ...

(.pt2) e:\stability_video>python scripts/sampling/simple_video_sample.py --input_path e:\stability_video\image.png --version sv3d_p --elevations_deg 10.0
Traceback (most recent call last):
  File "e:\stability_video\scripts\sampling\simple_video_sample.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

(.pt2) e:\stability_video>



omg your repository is such as complicate     MARK it  for only PROFESSIONALS !!!

**Comment by Marinades** [comment]
> python3 -m venv .pt2 activate.bat
> 
> (.pt2) pip install -r pt2.txt
> 
> install ...
> 
> in the end
> 
> ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10 ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none) ERROR: No matching distribution found for triton==2.0.0
> 
> install pip3 install . pip3 install -e git+https://github.com/Stability-AI/datapipelines.git@main#egg=sdata pip install hatch hatch build -t wheel
> 
> and again ...
> 
> (.pt2) e:\stability_video>python scripts/sampling/simple_video_sample.py --input_path e:\stability_video\image.png --version sv3d_p --elevations_deg 10.0 Traceback (most recent call last): File "e:\stability_video\scripts\sampling\simple_video_sample.py", line 9, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> (.pt2) e:\stability_video>
> 
> omg your repository is such as complicate MARK it for only PROFESSIONALS !!!

Some of your packages in pt2 were probably not installed, since triton failed to install. You need to resolve that first.

**Comment by lucaschalk** [comment]
> > python3 -m venv .pt2 activate.bat
> > (.pt2) pip install -r pt2.txt
> > install ...
> > in the end
> > ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10 ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none) ERROR: No matching distribution found for triton==2.0.0
> > install pip3 install . pip3 install -e git+https://github.com/Stability-AI/datapipelines.git@main#egg=sdata pip install hatch hatch build -t wheel
> > and again ...
> > (.pt2) e:\stability_video>python scripts/sampling/simple_video_sample.py --input_path e:\stability_video\image.png --version sv3d_p --elevations_deg 10.0 Traceback (most recent call last): File "e:\stability_video\scripts\sampling\simple_video_sample.py", line 9, in import cv2 ModuleNotFoundError: No module named 'cv2'
> > (.pt2) e:\stability_video>
> > omg your repository is such as complicate MARK it for only PROFESSIONALS !!!
> 
> Some of your packages in pt2 were probably not installed, since triton failed to install. You need to resolve that first.

this @kalle07  delete triton package and let all requirements install
