### ISSUE TITLE
TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

### ISSUE THREAD

**Issue by Alexandrsv** [Stability-AI/generative-models#338]
Error when generating video
svd, default params and "Decode t frames at a time" = 1

<details><summary>log</summary>

```
PYTHONPATH=. streamlit run scripts/demo/video_sampling.py --server.port 8008                                                                            ✔  generative-models  


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8008
  Network URL: http://192.168.0.10:8008

VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/svd.safetensors
2024-03-28 01:19:06.710 Uncaught app exception
Traceback (most recent call last):
  File "/home/alexandr/NeuralNetworks/generative-models/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/alexandr/NeuralNetworks/generative-models/scripts/demo/video_sampling.py", line 190, in <module>
    value_dict["cond_frames"] = img + cond_aug * torch.randn_like(img)
TypeError: randn_like(): argument 'input' (position 1) must be Tensor, not NoneType
Global seed set to 23
Global seed set to 23
Global seed set to 23
##############################  Sampling setting  ##############################
Sampler: EulerEDMSampler
Discretization: EDMDiscretization
Guider: LinearPredictionGuider
Sampling with EulerEDMSampler for 26 steps:   0%|                                                                                                                                                                    | 0/26 [00:00<?, ?it/s]/home/alexandr/NeuralNetworks/generative-models/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Sampling with EulerEDMSampler for 26 steps:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 25/26 [00:40<00:01,  1.60s/it]
2024-03-28 01:20:06.392 Uncaught app exception
Traceback (most recent call last):
  File "/home/alexandr/NeuralNetworks/generative-models/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/alexandr/NeuralNetworks/generative-models/scripts/demo/video_sampling.py", line 280, in <module>
    save_video_as_grid_and_mp4(samples, save_path, T, fps=saving_fps)
  File "/home/alexandr/NeuralNetworks/generative-models/scripts/demo/streamlit_helpers.py", line 912, in save_video_as_grid_and_mp4
    imageio.mimwrite(video_path, vid, fps=fps)
  File "/home/alexandr/NeuralNetworks/generative-models/venv/lib/python3.10/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/alexandr/NeuralNetworks/generative-models/venv/lib/python3.10/site-packages/imageio/plugins/tifffile_v3.py", line 224, in write
    self._fh.write(image, **kwargs)
TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

``` 

</details>

**Comment by cmh1027** [comment]
https://github.com/OpenTalker/SadTalker/issues/276#issuecomment-1570190070

**Comment by yjhong89** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-29T02:50:33
          
          
            * Subject : 
Re: [Stability-AI/generative-models] TypeError: TiffWriter.write() got an unexpected keyword argument 'fps' (Issue #338)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
