### ISSUE TITLE
Error loading safetensor files for svd and sv3d

### ISSUE THREAD

**Issue by mich889** [Stability-AI/generative-models#405]
I've installed sv3d and svd.safetensors from https://huggingface.co/stabilityai/stable-video-diffusion-img2vid and https://huggingface.co/stabilityai/sv3d/tree/main
but when running scripts/sampling/simple_video_sample.py or python scripts/sampling/simple_video_sample.py --input_path <path/to/image.png> --version sv3d_u
as stated in https://github.com/Stability-AI/generative-models?tab=readme-ov-file
im getting 
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

im on linux, python 3.10, could i get some help?
I've installed sv3d and svd.safetensors from https://huggingface.co/stabilityai/stable-video-diffusion-img2vid and https://huggingface.co/stabilityai/sv3d/tree/main
but when running scripts/sampling/simple_video_sample.py or python scripts/sampling/simple_video_sample.py --input_path <path/to/image.png> --version sv3d_u
as stated in https://github.com/Stability-AI/generative-models?tab=readme-ov-file
im getting 
Traceback (most recent call last):
  File "/home/mich889/generative-models/scripts/sampling/simple_video_sample.py", line 349, in <module>
    Fire(sample)
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/mich889/generative-models/scripts/sampling/simple_video_sample.py", line 98, in sample
    model, filter = load_model(
  File "/home/mich889/generative-models/scripts/sampling/simple_video_sample.py", line 340, in load_model
    model = instantiate_from_config(config.model).to(device).eval()
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/sgm/util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/sgm/models/diffusion.py", line 81, in __init__
    self.init_from_ckpt(ckpt_path)
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/sgm/models/diffusion.py", line 92, in init_from_ckpt
    sd = load_safetensors(path)
  File "/home/mich889/miniconda3/envs/svd/lib/python3.10/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

im on linux, python 3.10, could i get some help?

**Comment by LukeLIN-web** [comment]
I don't meet this problem.

**Comment by LukeLIN-web** [comment]
I meet another problem , packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/home.conda/envs/svd/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/home/conda/envs/svd/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid configuration argument
